Add PaymentIDRepository
wmde/fundraising-payments pull request #63
Opened 2022-02-21 09:32 UTC by Abban

This adds a new schema, repository and use case
that allows donations or memberships to request a
new unique payment ID in order to create a
payment entity.

Also added is the required infrastructure for
the Doctrine annotation mapping.

Ticket: https://phabricator.wikimedia.org/T301115

2022-02-22 13:17 UTC, gbirke requested changes
Different than I imagined, but I'm fine with using an entity. It has the benefit of automated DB setup and being database-independent. 

However, it has the following drawbacks:

- higher levels of PHPStan (see #61 ) will probably complain about the entity (nullable property without constructor and non-nullable getter.
- A table filling up with IDs (instead of having a table with exactly one entry). Not a big deal with modern hard drives and SSD
- I wanted to use the same DBMS (MySQL) for tests that test interaction with the database. It'll be harder to set up and and run in CI, but it'll catch subtle DBMS differences. That's one of the reasons (extending travis with MySQL services, adding a docker environment for local tests) why we estimated the original with 8 points.

2022-02-22 13:17 UTC, gbirke commented on src/UseCases/GetPaymentID/GetPaymentIDUseCase.php
> +}
You can drop this class and its test. Getting a payment id is an internal service of the payment domain, whereas "use cases" are the public API of a bounded context.

2022-02-22 17:50 UTC, gbirke commented
Sorry that my review comment did not include a clear call to action / what still needs to be done.
I'd be OK with minor changes:

- removing the use case class
- rebasing onto current main and seeing if there are PHPStan errors to be fixed (you may add exemptions for the nullable types in the PHP file or install the phpstan doctrine extension to see if that helps)
- Adding a comment on why the ID class exists

If you like to do more, I would be happy about one or more of the following changes:

- the database test uses mysql (which means changing docker-compose to include mysql and fiddling with the test environments (docker-compose, travis) to use that). 
- Maybe migrate from Travis to github actions (See https://ovirium.com/blog/how-to-make-mysql-work-in-your-github-actions/ for the mysql part)
- we drop the entity and use pure SQL instead, see [my gist example](https://gist.github.com/gbirke/6c7d67b3f4469dd3a05e269f8469f56b). We can create a class that creates/drops the necessary table and its entry with the Doctrine DBAL schema and query methods and include calls to that class in the test environment setup (for prod, we'd create a separate migration class).

2022-02-28 18:11 UTC, gbirke approved these changes
I like the changes, thanks!

2022-03-01 07:02 UTC, Abban commented
We could modify the `getNewID()` method to cache the id, then delete the record, then return the id. MySQLs auto increment should remember the current highest index for us.

2022-03-07 12:26 UTC, gbirke requested changes
The tests fail intermittently in CI an ond my local machine (esp. when starting with fresh containers). To me, this looks like there is a small amount of time between the DB container being "up" and the DB accepting connections. If I run `docker-compose up -d` and then `make phpunit-with-coverage`, it works consistently, but that's no solution for CI.
Looks like the `depends_on` is not doing what it's supposed to do. Can you look into it?
Alternatively, you can check if adding a `start_dependencies` service like we do in fundraising app will help.

2022-03-07 12:26 UTC, gbirke commented on Makefile
> -	docker-compose -f docker-compose.yml -f docker-compose.debug.yml run --rm --no-deps -e XDEBUG_MODE=coverage app_debug ./vendor/bin/phpunit $(COVERAGE_FLAGS)
The `test` target now also needs dependencies

2022-03-07 12:26 UTC, gbirke commented on src/Domain/Model/PaymentID.php
> + * easier
```suggestion
 * This class and its Doctrine mapping is only used in the test environment to quickly create and tear down the payment_id table. The production environment uses a migration to set up the table.
  * @internal
```

2022-03-07 14:57 UTC, gbirke commented
I've looked further into this and found out that `depends_on` was removed for docker-compose >= 3.0. I suggest [following the official documentation](https://docs.docker.com/compose/startup-order/) and adding [wait-for-it.sh](https://github.com/vishnubob/wait-for-it) or [wait-for](https://github.com/Eficode/wait-for) to our Dockerfile, prepending the call to `./vendor/bin/phpunit` with the wait-for script. `wait-for` is probably better suited for the alpine image.

2022-03-09 06:32 UTC, Abban commented on docker-compose.debug.yml
> +  database:
This was me trying to get Docker to wait for the database service to be set up before starting the app service. `depends_on` only waits for the service to start, not for it to finish it's internal setup, which is why it fails for you randomly. We can have a chat about it in the daily.

2022-03-11 08:46 UTC, merged